Repository YAPP-Github/20th-Web-Team-2-FE, pull requests merged in 2022-06, with the labels that each got.

#30 Feat: Range input 레이아웃, 버그 수정
  src/components/base/MultiRangeSlider.tsx
  src/components/base/Test.tsx
Labels: Fix, Design

#28 Feature/email page
  src/components/authMail/AuthCodeForm.tsx
  src/components/authMail/EmailForm.tsx
  src/components/authMail/index.ts
  src/components/base/Button/Button.tsx
  src/components/base/Input.tsx
  src/components/survey/SurveyTemplate.tsx
  src/components/survey/index.ts
  src/hooks/common/index.ts
  src/hooks/common/useCountdown.ts
  src/hooks/common/useForm.ts
  src/lib/styles/palette.ts
  src/lib/styles/styledComponents.ts
  src/pages/AuthMail.tsx
  src/utils/validations.ts
Labels: Feat

#33 Feat: 학교 검색 컴포넌트
  src/assets/img/DeleteIcon.png
  src/assets/img/SearchIcon.png
  src/assets/img/index.ts
  src/components/domain/survey/SchoolSearch.tsx
  src/mock/schools.ts
  src/pages/Survey.tsx
Labels: Feat

#39 Feature/checkbox survey
  src/components/base/CheckBox.tsx
  src/pages/FoundPath.tsx
  src/router/Path.ts
  src/router/Routing.tsx
Labels: Feat, Design

#41 Feature/type of meeting survey
  src/components/base/ChoiceButton.tsx
  src/components/domain/TypeOfMeeting.tsx
  src/components/domain/index.ts
  src/lib/styles/styledComponents.ts
  src/pages/TypeOfMeetingSurvey.tsx
  src/router/Path.ts
  src/router/Routing.tsx
Labels: Feat

#47 Refactor/branch name
  src/components/base/Button.tsx
  src/components/base/index.ts
  src/components/domain/index.ts
  src/components/domain/landing/index.ts
  src/components/domain/survey/SurveyTemplate.tsx
  src/components/domain/survey/TypeOfMeeting.tsx
  src/components/domain/survey/index.ts
  src/components/survey/index.ts
  src/hooks/common/index.ts
  src/hooks/index.ts
  src/pages/AuthMail.tsx
  src/pages/FoundPath.tsx
  src/pages/LandingPage.tsx
  src/pages/Survey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/pages/index.ts
  src/router/Routing.tsx
Labels: Refactor

#45 Feature/SimpleRangeSlider
  src/components/base/SimpleRangeSlider.tsx
  src/components/base/index.ts
Labels: Feat

#43 Feature/meeting survey 5
  src/components/domain/survey/AgeBox.tsx
  src/components/domain/survey/GenderBox.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/components/domain/survey/index.ts
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/index.ts
Labels: Feat

#52 Featrue/PreferAverageAgeHeightSurvey#10
  src/components/domain/survey/AgeBox.tsx
  src/components/domain/survey/HeightBox.tsx
  src/components/domain/survey/index.ts
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
Labels: Feat

#60 Feature/our dprt height
  src/components/domain/survey/AgeBox.tsx
  src/components/domain/survey/ChooseFourBox.tsx
  src/components/domain/survey/HeightBox.tsx
  src/components/domain/survey/TypeOfMeetingBox.tsx
  src/components/domain/survey/index.ts
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/PreferDepartmentsSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/router/Path.ts
  src/router/Routing.tsx
Labels: Feat

#62 Fix/type of meeting
  src/components/domain/survey/ChooseFourBox.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/router/Routing.tsx
Labels: Fix

#63 design: PreferDepartmentsSurvey 문구 수정
  src/components/domain/survey/ChooseFourBox.tsx
  src/pages/PreferDepartmentsSurvey.tsx
Labels: Design, Comment

#65 feat: MindsetSurvey, PlaySurvey
  src/pages/MindsetSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/router/Path.ts
Labels: Feat

#68 Feat: AuthMail 학교 추가하기 링크 추가
  src/pages/AuthMail.tsx
Labels: Feat

#73 fix: 번들된 타입 바로 가져오는 에러 수정
  src/types/data.ts
Labels: Fix

#85 Chore, Feat: recoil, recoil-persist 설치, 전역 상태 base 설정
  package.json
  src/atoms/datingState.ts
  src/atoms/meetingState.ts
  src/main.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/types/dating.ts
  src/types/meeting.ts
  yarn.lock
Labels: Feat, Chore

#94 [Fix & Refactor] 컨텐츠 연결 시 버그 개선
  src/components/domain/survey/SearchSelector.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/hooks/agreement/useAgreementCheck.ts
  src/hooks/agreement/useFoundPathCheck.ts
  src/lib/styles/palette.ts
  src/mock/schools.ts
  src/pages/AgreementSurvey.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/ChannelSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/utils/buttons.ts
Labels: Fix, Refactor

#95 Style: 오타 수정
  src/utils/buttons.ts
Labels: Fix

#96 style: button.ts 포맷 수정
  src/utils/buttons.ts
Labels: Style

#97 matching Page #31~33.5
  src/assets/img/Complete.png
  src/assets/img/CopyIcon.png
  src/assets/img/MatchingFail.png
  src/assets/img/MatchingSuccess.png
  src/assets/img/Waiting.png
  src/assets/img/index.ts
  src/components/domain/matching/CompleteBox.tsx
  src/components/domain/matching/EndBox.tsx
  src/components/domain/matching/KakaoCopyBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/SuccessBox.tsx
  src/components/domain/matching/UserHeader.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/hooks/common/AddCommaFunction.ts
  src/lib/styles/styledComponents.ts
  src/pages/MatchingPage.tsx
  src/router/Routing.tsx
Labels: Feat, Design

#99 Feat: 미팅 설문 상태 recoil & sessionStorage로 변경
  src/atoms/meetingState.ts
  src/components/base/MultiRangeSlider.tsx
  src/components/base/SimpleRangeSlider.tsx
  src/components/domain/survey/AgeBox.tsx
  src/components/domain/survey/HeightBox.tsx
  src/hooks/common/index.ts
  src/hooks/common/useMeetingSessionState.ts
  src/hooks/common/useSesstionStorage.ts
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/IsAbroadSurvey.tsx
  src/pages/MindsetSurvey.tsx
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/types/constants/constant.ts
  src/types/constants/department.ts
  src/types/enums.ts
  src/types/meeting.ts
Labels: Feat

#102 Release 0.1.0
  .github/workflows/release-tag.yml
  src/assets/img/Complete.png
  src/assets/img/CopyIcon.png
  src/assets/img/MatchingFail.png
  src/assets/img/MatchingSuccess.png
  src/assets/img/Waiting.png
  src/assets/img/index.ts
  src/atoms/meetingState.ts
  src/components/base/MultiRangeSlider.tsx
  src/components/base/SimpleRangeSlider.tsx
  src/components/domain/matching/CompleteBox.tsx
  src/components/domain/matching/EndBox.tsx
  src/components/domain/matching/KakaoCopyBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/SuccessBox.tsx
  src/components/domain/matching/UserHeader.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/components/domain/survey/AgeBox.tsx
  src/components/domain/survey/HeightBox.tsx
  src/components/domain/survey/SearchSelector.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/hooks/agreement/useAgreementCheck.ts
  src/hooks/agreement/useFoundPathCheck.ts
  src/hooks/common/AddCommaFunction.ts
  src/hooks/common/index.ts
  src/hooks/common/useMeetingSessionState.ts
  src/hooks/common/useSesstionStorage.ts
  src/lib/styles/palette.ts
  src/lib/styles/styledComponents.ts
  src/mock/schools.ts
  src/pages/AgreementSurvey.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/ChannelSurvey.tsx
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/IsAbroadSurvey.tsx
  src/pages/MatchingPage.tsx
  src/pages/MindsetSurvey.tsx
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/constants/constant.ts
  src/types/constants/department.ts
  src/types/enums.ts
  src/types/meeting.ts
  src/utils/buttons.ts
Labels: Release

#106 Release 0.1.1
  .github/workflows/release-tag.yml
Labels: Release
