Repository YAPP-Github/20th-Web-Team-2-FE, pull requests merged in 2022-05, with the labels that each got.

#5 Feat: Button 컴포넌트 구현
  src/App.tsx
  src/components/Test.tsx
  src/components/base/Button/Button.tsx
  src/components/base/index.ts
  src/components/index.ts
Labels: Feat

#8 Feat: 프로그래스바, 양방향 Range Input 컴포넌트 작성
  .eslintrc.js
  .prettierrc
  package.json
  src/App.tsx
  src/components/base/MultiRangeSlider.tsx
  src/components/base/ProgressBar.tsx
  src/lib/styles/palette.ts
  yarn.lock
Labels: Feat

#9 Feat/input
  src/components/base/Input.tsx
  src/components/base/index.ts
Labels: Feat

#15 Feat/router
  src/components/base/Input.tsx
  src/router/Path.ts
  src/router/Routing.tsx
Labels: Feat

#13 Design: 가변 Pretendard 폰트 적용
  index.html
  src/lib/styles/globalStyles.ts
Labels: Design

#21 refactor: 버튼 타입 오류 수정, 시안 반영
  src/components/base/Button/Button.tsx
  src/lib/styles/palette.ts
Labels: Refactor

#24 Design: 인증 / 설문 레이아웃
  src/components/base/ProgressBar.tsx
  src/components/base/Test.tsx
  src/components/survey/SurveyTemplate.tsx
  src/lib/styles/globalStyles.ts
  src/pages/AuthMail.tsx
  src/pages/Survey.tsx
  src/router/Routing.tsx
Labels: Feat, Design

#23 Chore: 기본 페이지들 라우터 추가
  src/App.tsx
  src/components/base/ProgressBar.tsx
  src/components/base/Test.tsx
  src/components/survey/SurveyTemplate.tsx
  src/lib/styles/globalStyles.ts
  src/pages/AuthMail.tsx
  src/pages/Landing.tsx
  src/pages/NotFound.tsx
  src/pages/Survey.tsx
  src/router/Path.ts
  src/router/Routing.tsx
Labels: Chore

#25 Design/landing page
  src/assets/img/Logo.png
  src/assets/img/RadiousLogo.png
  src/assets/img/StringLogo.png
  src/assets/img/index.ts
  src/assets/index.ts
  src/components/base/Button/Button.tsx
  src/components/base/Modal.tsx
  src/components/base/index.ts
  src/components/domain/landing/LandingContainer.tsx
  src/components/domain/landing/LandingFooter.tsx
  src/lib/styles/palette.ts
  src/pages/Landing.tsx
  src/pages/LandingPage.tsx
  src/router/Routing.tsx
Labels: Design, Rename
