Repository YAPP-Github/20th-Web-Team-2-FE, pull requests merged in 2022-07, with the labels that each got.

#107 dating 관련 path 설정, session 적용
  src/atoms/datingState.ts
  src/hooks/agreement/useChannelCheck.ts
  src/hooks/common/index.ts
  src/hooks/common/useDatingSessionState.ts
  src/hooks/common/useNavigate.ts
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AgreementSurvey.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/ChannelSurvey.tsx
  src/pages/DomesticAreasSurvey.tsx
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/IsAbroadSurvey.tsx
  src/pages/KakaoIdSurvey.tsx
  src/pages/MindsetSurvey.tsx
  src/pages/MyBodySmoke.tsx
  src/pages/MyDateCount.tsx
  src/pages/MyDepartmentCharacter.tsx
  src/pages/MyGenderAge.tsx
  src/pages/MyMbtiHeight.tsx
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/PreferBodyDateCountSurvey.tsx
  src/pages/PreferDepartmentCharacterSurvey.tsx
  src/pages/PreferDepartmentsSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/types/constants/body.ts
  src/types/constants/characteristic.ts
  src/types/constants/charater.ts
  src/types/constants/dcount.ts
  src/types/constants/department.ts
  src/types/dating.ts
  src/types/meeting.ts
Labels: Feat

#140 feat: 테스트 로그인 페이지 구현
  src/components/domain/landing/LandingContainer.tsx
  src/components/testLogin/LoginForm.tsx
  src/components/testLogin/index.ts
  src/hooks/common/useForm.ts
  src/lib/api/index.ts
  src/lib/api/login.ts
  src/lib/constants/index.ts
  src/pages/TestLogin.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/user.ts
Labels: Feat

#142 feat: 임시로 join 후 login post
  src/lib/api/login.ts
Labels: Feat

#146 fix: test-login에 그냥 Join도 추가
  src/lib/api/login.ts
  src/pages/TestLogin.tsx
Labels: Fix

#160 feat: 리매칭 연결
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/buttons/EndButton.tsx
  src/lib/api/meeting.ts
  src/pages/MatchingPage.tsx
Labels: Feat

#164 Feat: 출신학교
  src/components/domain/survey/SearchSelector.tsx
  src/pages/OurUniversitiesSurvey.tsx
Labels: Feat

#167 feat: 본인 키 에러 수정, 에러 문구 로직 수정
  src/pages/MyMbtiHeight.tsx
Labels: Fix

#162 feat: 어드민 기초 구현
  src/lib/api/admin.ts
  src/pages/AdminPage.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/user.ts
Labels: Feat

#166 Release 0.1.6
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/buttons/EndButton.tsx
  src/components/domain/survey/SearchSelector.tsx
  src/components/header/DatingInfoBox.tsx
  src/components/header/MeetingInfoBox.tsx
  src/hooks/survey/useAboardAreaLoad.ts
  src/hooks/survey/useUnivLoad.ts
  src/lib/api/admin.ts
  src/lib/api/area.ts
  src/lib/api/index.ts
  src/lib/api/login.ts
  src/lib/api/meeting.ts
  src/lib/api/university.ts
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AdminPage.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/MatchingPage.tsx
  src/pages/MyMbtiHeight.tsx
  src/pages/OauthKakao.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/TestLogin.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/user.ts
Labels: Release

#170 feat: MBTI 옵션 리스트로 변경
  src/components/domain/survey/UnitSelector.tsx
  src/components/domain/survey/index.ts
  src/pages/MyMbtiHeight.tsx
  src/pages/OurUniversitiesSurvey.tsx
Labels: Feat

#171 feat: 미팅 가능 도시 필수값으로 변경
  src/pages/AbroadAreasSurvey.tsx
Labels: Feat

#176 feat: all routing 체크
  src/assets/img/Logout.png
  src/assets/img/index.ts
  src/components/domain/matching/WaitingBox.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/components/header/MenuBlock.tsx
  src/hooks/agreement/useAgreementCheck.ts
  src/lib/api/login.ts
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/EndSurvey.tsx
  src/pages/KakaoIdSurvey.tsx
  src/pages/MyBodySmoke.tsx
  src/pages/MyDateCount.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/constants/dcount.ts
  src/utils/converson/conversionDateCount.ts
Labels: Feat

#168 Release 0.1.7
  .env.development
  .env.production
  src/assets/img/Logout.png
  src/assets/img/index.ts
  src/components/authMail/AuthCodeForm.tsx
  src/components/domain/landing/LandingContainer.tsx
  src/components/domain/matching/CompleteBox.tsx
  src/components/domain/matching/DatingEndBox.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/MeetingEndBox.tsx
  src/components/domain/matching/SuccessBox.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/components/domain/matching/buttons/WaitingButton.tsx
  src/components/domain/survey/SearchSelector.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/components/domain/survey/UnitSelector.tsx
  src/components/domain/survey/index.ts
  src/components/header/MenuBlock.tsx
  src/hooks/agreement/useAgreementCheck.ts
  src/hooks/common/index.ts
  src/hooks/common/useAuthNumber.ts
  src/hooks/common/useCountdown.ts
  src/hooks/common/useDateLabel.ts
  src/lib/api/dating.ts
  src/lib/api/email.ts
  src/lib/api/login.ts
  src/lib/api/meeting.ts
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AuthMail.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/EndSurvey.tsx
  src/pages/KakaoIdSurvey.tsx
  src/pages/MatchingPage.tsx
  src/pages/MyBodySmoke.tsx
  src/pages/MyDateCount.tsx
  src/pages/MyMbtiHeight.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/index.ts
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/area.ts
  src/types/constants/dcount.ts
  src/types/dating.ts
  src/types/meeting.ts
  src/types/user.ts
  src/utils/converson/conversionDateCount.ts
Labels: Release

#188 feat: 백앤드 이미지 저장
  src/assets/img/email-01.png
  src/assets/img/email-02.png
  src/assets/img/email-03.png
  src/assets/img/email-04.png
  src/assets/img/email-05.png
  src/assets/img/email-06.png
Labels: Feat

#187 Release 0.1.8
  src/assets/img/email-01.png
  src/assets/img/email-02.png
  src/assets/img/email-03.png
  src/assets/img/email-04.png
  src/assets/img/email-05.png
  src/assets/img/email-06.png
  src/components/base/LoginCheck.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/MeetingEndBox.tsx
  src/components/domain/survey/Template.tsx
  src/components/header/UserHeader.tsx
  src/hooks/common/useDateLabel.ts
  src/router/Routing.tsx
Labels: Release

#191 Release 0.1.9
  src/components/base/MultiRangeSlider.tsx
  src/components/base/SimpleRangeSlider.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/pages/AuthMail.tsx
Labels: Release

#194 fix: login.ts -> user.ts 변경
  src/components/header/MenuBlock.tsx
  src/lib/api/user.ts
  src/pages/TestLogin.tsx
Labels: Fix

#201 Feat: 매칭 실패 페이지 구현
  src/components/domain/matching/FailBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/buttons/EndButton.tsx
  src/lib/api/meeting.ts
  src/pages/MatchingPage.tsx
Labels: Feat

#203 Feat, Style: 문구수정, UI 수정
  src/assets/img/CopyWhiteIcon.png
  src/assets/img/index.ts
  src/components/domain/landing/LandingContainer.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/SuccessBox.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/components/domain/matching/buttons/SuccessButton.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AgreementSurvey.tsx
  src/pages/AuthMail.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/ChannelSurvey.tsx
  src/pages/DomesticAreasSurvey.tsx
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/IsAbroadSurvey.tsx
  src/pages/KakaoIdSurvey.tsx
  src/pages/MindsetSurvey.tsx
  src/pages/MyBodySmoke.tsx
  src/pages/MyDateCount.tsx
  src/pages/MyDepartmentCharacter.tsx
  src/pages/MyGenderAge.tsx
  src/pages/MyMbtiHeight.tsx
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/PreferBodyDateCountSurvey.tsx
  src/pages/PreferDepartmentCharacterSurvey.tsx
  src/pages/PreferDepartmentsSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
Labels: Feat, Style

#206 Release 0.1.14
  src/assets/img/CopyWhiteIcon.png
  src/assets/img/index.ts
  src/components/domain/landing/LandingContainer.tsx
  src/components/domain/matching/FailBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/SuccessBox.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/components/domain/matching/buttons/EndButton.tsx
  src/components/domain/matching/buttons/SuccessButton.tsx
  src/components/domain/survey/SurveyTemplate.tsx
  src/lib/api/meeting.ts
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AgreementSurvey.tsx
  src/pages/AuthMail.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/ChannelSurvey.tsx
  src/pages/DomesticAreasSurvey.tsx
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/IsAbroadSurvey.tsx
  src/pages/KakaoIdSurvey.tsx
  src/pages/MatchingPage.tsx
  src/pages/MindsetSurvey.tsx
  src/pages/MyBodySmoke.tsx
  src/pages/MyDateCount.tsx
  src/pages/MyDepartmentCharacter.tsx
  src/pages/MyGenderAge.tsx
  src/pages/MyMbtiHeight.tsx
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/PreferBodyDateCountSurvey.tsx
  src/pages/PreferDepartmentCharacterSurvey.tsx
  src/pages/PreferDepartmentsSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
Labels: Release

#208 feat: 코드로 로직 분기, 여성용 UI 만듦
  src/components/domain/matching/CompleteBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/buttons/FemaleSuccessButton.tsx
  src/pages/MatchingPage.tsx
  src/types/dating.ts
  src/types/meeting.ts
Labels: Feat

#209 Release 0.1.15
  src/components/domain/matching/CompleteBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/buttons/FemaleSuccessButton.tsx
  src/pages/MatchingPage.tsx
  src/types/dating.ts
  src/types/meeting.ts
Labels: Release

#211 feat: 다시 매칭 모달 추가
  src/components/base/Modal.tsx
  src/components/domain/matching/buttons/EndButton.tsx
Labels: Feat

#210 Release 0.1.16
  src/components/base/Modal.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/components/domain/matching/buttons/EndButton.tsx
  src/components/domain/matching/buttons/NoneButton.tsx
  src/components/domain/survey/SurveyTemplate.tsx
Labels: Release

#215 Feature/logout
  src/components/header/MenuBlock.tsx
  src/lib/api/user.ts
Labels: Feat

#216 feat: MathcingTemplete import 구조 개선
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/buttons/index.ts
  src/components/domain/matching/index.ts
  src/pages/MatchingPage.tsx
Labels: Feat

#219 feat: 매칭 취소 페이지 구현
  src/components/domain/matching/CancelBox.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/MatchingTemplete.tsx
  src/components/domain/matching/index.ts
  src/pages/MatchingPage.tsx
  src/types/dating.ts
  src/types/meeting.ts
Labels: Design

#224 feat: 결과 성사 페이지 애니메이션 추가
  package.json
  src/assets/lotties/index.ts
  src/assets/lotties/party.json
  src/components/domain/matching/MatchingStateTitle.tsx
  yarn.lock
Labels: Design

#228 feat: waiting 애니메이션 추가
  src/assets/lotties/index.ts
  src/assets/lotties/waiting.json
  src/components/base/IntervalPoints.tsx
  src/components/base/index.ts
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/hooks/survey/useIntervalPoint.ts
Labels: Design

#225 Release 1.1.18
  package.json
  src/assets/lotties/index.ts
  src/assets/lotties/party.json
  src/assets/lotties/waiting.json
  src/components/base/IntervalPoints.tsx
  src/components/base/index.ts
  src/components/domain/landing/LandingContainer.tsx
  src/components/domain/matching/MatchingStateTitle.tsx
  src/components/domain/matching/WaitingBox.tsx
  src/components/header/MeetingInfoBox.tsx
  src/hooks/survey/useIntervalPoint.ts
  src/hooks/survey/useUpdateSurvey.ts
  src/lib/api/area.ts
  src/pages/DomesticAreasSurvey.tsx
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/IsAbroadSurvey.tsx
  src/pages/MindsetSurvey.tsx
  src/pages/MyGenderAge.tsx
  src/pages/OurDepartmentsAverageHeightSurvey.tsx
  src/pages/OurUniversitiesSurvey.tsx
  src/pages/PlaySurvey.tsx
  src/pages/PreferAverageAgeHeightSurvey.tsx
  src/pages/PreferDepartmentsSurvey.tsx
  src/pages/TypeOfMeetingSurvey.tsx
  src/router/Path.ts
  src/router/Routing.tsx
  src/types/constants/constant.ts
  src/types/meeting.ts
  yarn.lock
Labels: Release

#233 feat: 일반 로그인 삭제
  src/components/domain/landing/LandingContainer.tsx
Labels: Fix

#235 fix: Sign 슬라이더 바깥으로 넘어가는 이슈 수정
  src/components/base/SimpleRangeSlider.tsx
Labels: Fix

#236 feat: 바로 매칭해드릴게요 bottom padding 추가
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/MyGenderAge.tsx
Labels: Design

#239 fix: 첫 마운트 시 선택한 학교 목록 렌더링
  src/components/domain/survey/SearchSelector.tsx
Labels: Fix

#240 fix: 도시 하나 이상 클릭하면 다음버튼 활성화
  src/pages/AbroadAreasSurvey.tsx
Labels: Fix

#234 Release 1.2.0
  src/components/authMail/AuthCodeForm.tsx
  src/components/authMail/EmailForm.tsx
  src/components/base/Input.tsx
  src/components/base/SimpleRangeSlider.tsx
  src/components/domain/landing/LandingContainer.tsx
  src/components/domain/survey/SearchSelector.tsx
  src/components/header/DatingInfoBox.tsx
  src/components/header/MeetingInfoBox.tsx
  src/hooks/survey/useUpdateSurvey.ts
  src/lib/api/dating.ts
  src/pages/AbroadAreasSurvey.tsx
  src/pages/AuthMail.tsx
  src/pages/AvoidUniversitiesSurvey.tsx
  src/pages/GenderAverageAgeSurvey.tsx
  src/pages/MyBodySmoke.tsx
  src/pages/MyDateCount.tsx
  src/pages/MyDepartmentCharacter.tsx
  src/pages/MyGenderAge.tsx
  src/pages/MyMbtiHeight.tsx
  src/pages/OauthKakao.tsx
  src/pages/PreferBodyDateCountSurvey.tsx
  src/pages/PreferDepartmentCharacterSurvey.tsx
  src/pages/PreferUniversitiesSurvey.tsx
Labels: Release
